export default {
  maxexpandId: 95,
  treelist: [{
    id: 1,
    name: '北京市',
    ProSort: 1,
    remark: '直辖市',
    pid: '',
    isEdit: false,
    children: [{
      id: 35,
      name: '朝阳区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 36,
      name: '海淀区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 37,
      name: '房山区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 38,
      name: '丰台区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 39,
      name: '昌平区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 40,
      name: '大兴区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }]
  }, {
    id: 33,
    name: '澳门特别行政区',
    ProSort: 33,
    remark: '特别行政区',
    pid: '',
    isEdit: false,
    children: []
  }, {
    id: 34,
    name: '香港特别行政区',
    ProSort: 34,
    remark: '特别行政区',
    pid: '',
    isEdit: false,
    children: [{
      id: 82,
      name: '湾仔区',
      pid: 34,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 95,
      name: '西贡区',
      pid: 34,
      remark: '',
      isEdit: false,
      children: []
    }]
  }]
}
